-- 001: Bus route -> ordered stops
-- Source: wbtc_bus_routes.csv
-- CSV columns: vehicle_type, route_no, depot, stop_sequence_no, stop_name
-- operator is written as a constant (WBTC) because the source has no operator
-- column. DDL is reproduced verbatim from the specification, section 5.
--
-- NOTE ON "IF NOT EXISTS": deliberately absent. Each migration runs in its own
-- transaction and is recorded in schema_migrations, so a file that has not run
-- yet must be creating its tables for the first time. "IF NOT EXISTS" turns a
-- name collision with a differently-shaped table into a silent no-op, and the
-- failure then surfaces as a baffling "column does not exist" several
-- statements later. A hard "relation already exists" error is the honest one.
-- The indexes below keep IF NOT EXISTS because they are purely additive.

CREATE TABLE bus_route_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator TEXT NOT NULL,
    vehicle_type TEXT NOT NULL DEFAULT 'bus',
    route_no TEXT NOT NULL,
    depot TEXT,
    stop_sequence_no INTEGER NOT NULL,
    stop_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bus_route_stops_route_no
ON bus_route_stops(route_no);

CREATE INDEX IF NOT EXISTS idx_bus_route_stops_stop_name
ON bus_route_stops(stop_name);

CREATE INDEX IF NOT EXISTS idx_bus_route_stops_route_sequence
ON bus_route_stops(route_no, stop_sequence_no);

CREATE INDEX IF NOT EXISTS idx_bus_route_stops_operator
ON bus_route_stops(operator);

CREATE INDEX IF NOT EXISTS idx_bus_route_stops_operator_route
ON bus_route_stops(operator, route_no);

CREATE UNIQUE INDEX IF NOT EXISTS uq_bus_route_stop_sequence
ON bus_route_stops(operator, route_no, stop_sequence_no);
