-- 002: Bus timetable
-- Source: wbtc_bus_timetable_final.csv
-- CSV columns: operator, route_no, trip_no, direction_id, origin, destination,
--              departure_time, arrival_time, source_image_order
--
-- Note (spec section 6): route_no alone does NOT identify a trip. The timetable
-- identity is route_no + trip_no + direction_id. The source operator value
-- (which includes CSTC) is preserved as-is and is never overwritten with WBTC.

CREATE TABLE bus_timetables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator TEXT,
    route_no TEXT NOT NULL,
    trip_no INTEGER NOT NULL,
    direction_id INTEGER NOT NULL,
    origin TEXT,
    destination TEXT,
    departure_time TIME,
    arrival_time TIME,
    source_image_order INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bus_timetables_route_no
ON bus_timetables(route_no);

CREATE INDEX IF NOT EXISTS idx_bus_timetables_route_trip
ON bus_timetables(route_no, trip_no);

CREATE INDEX IF NOT EXISTS idx_bus_timetables_departure
ON bus_timetables(departure_time);

CREATE INDEX IF NOT EXISTS idx_bus_timetables_route_direction
ON bus_timetables(route_no, direction_id);

CREATE INDEX IF NOT EXISTS idx_bus_timetables_operator_route
ON bus_timetables(operator, route_no);
