-- 003: Tram route -> ordered stops
-- Source: wbtc_tram_routes.csv
-- CSV columns: id, vehicle_type, route_no, depot, stop_sequence_no, stop_name
--
-- NOTE: the real file carries a leading `id` column that the specification does
-- not list. It is a source-file artifact, not transport data, so it is not
-- stored. All other columns map 1:1.
--
-- stop_sequence_no is NULLABLE here: the tram source may have no sequence, and
-- the specification requires empty values to become SQL NULL, never 0.
-- The unique index below still behaves correctly because NULLs are distinct in
-- PostgreSQL unique indexes, so a route with many unsequenced stops is valid.
--
-- See migration 001 for why CREATE TABLE here has no IF NOT EXISTS.

CREATE TABLE tram_route_stops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator TEXT NOT NULL DEFAULT 'WBTC',
    vehicle_type TEXT NOT NULL DEFAULT 'tram',
    route_no TEXT NOT NULL,
    depot TEXT,
    stop_sequence_no INTEGER,
    stop_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tram_route_stops_route_no
ON tram_route_stops(route_no);

CREATE INDEX IF NOT EXISTS idx_tram_route_stops_stop_name
ON tram_route_stops(stop_name);

CREATE INDEX IF NOT EXISTS idx_tram_route_stops_route_sequence
ON tram_route_stops(route_no, stop_sequence_no);

CREATE INDEX IF NOT EXISTS idx_tram_route_stops_operator
ON tram_route_stops(operator);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tram_route_stop_sequence
ON tram_route_stops(operator, route_no, stop_sequence_no);
