-- 005: Route alias map + data-quality bookkeeping
--
-- WHY THIS EXISTS
-- ---------------
-- `wbtc_bus_routes.csv` and `wbtc_bus_timetable_final.csv` use DIFFERENT
-- route_no namespaces:
--   route-stop file : C-11, T-11, C-27, D1, ORD-1, C-11/1, T-2 (Khidirpur)
--   timetable file  : 11A, 14, 14A, 15, 33, 6, 7C, AC-1, ... AC-41
-- Only 2 of 67 timetable route numbers (AC-3, AC-4) appear in the route-stop
-- file.
--
-- Specification section 28 forbids fabricating data and section 18 requires
-- preserving source values, so this backend does NOT guess that "C-11" means
-- "11". Instead the linkage is a data table that ships EMPTY. Until it is
-- populated, the journey planner transparently falls back to static estimated
-- travel times (spec section 22) and `GET /api/bus/diagnostics` reports the
-- coverage gap.
--
-- The table is mode-agnostic, so a future Metro or Ferry import can use it too.

CREATE TABLE route_aliases (
    mode                 TEXT NOT NULL,
    -- Route number as it appears in the ROUTE-STOP source.
    source_route_no      TEXT NOT NULL,
    -- Route number as it appears in the TIMETABLE source.
    target_route_no      TEXT NOT NULL,
    -- Provenance for the mapping, so a human can audit every link.
    note                 TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (mode, source_route_no, target_route_no)
);

CREATE INDEX IF NOT EXISTS idx_route_aliases_source
ON route_aliases(mode, source_route_no);

CREATE INDEX IF NOT EXISTS idx_route_aliases_target
ON route_aliases(mode, target_route_no);

-- Records what each import run actually accepted and rejected, so data quality
-- is observable over HTTP instead of being buried in importer logs.
CREATE TABLE import_runs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file   TEXT NOT NULL,
    target_table  TEXT NOT NULL,
    mode          TEXT NOT NULL,
    operator      TEXT,
    rows_read     INTEGER NOT NULL DEFAULT 0,
    rows_inserted INTEGER NOT NULL DEFAULT 0,
    rows_rejected INTEGER NOT NULL DEFAULT 0,
    -- JSON array of { row, reason } for every rejected row.
    rejections    JSONB NOT NULL DEFAULT '[]'::jsonb,
    notes         JSONB NOT NULL DEFAULT '[]'::jsonb,
    started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_import_runs_source_file
ON import_runs(source_file, started_at DESC);
